Corriere/Controllers/RegistrationController.cs
using System;
using System.Configuration;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using Corriere.Models;

namespace Corriere.Controllers
{
    public class RegistrationController : Controller
    {
        private static string GetConnectionString()
        {
            return ConfigurationManager.ConnectionStrings["db"].ConnectionString;
        }

        [HttpGet]
        public ActionResult UserRegistration()
        {
            var model = new UserRegistrationViewModel();
            return View("~/Views/Registration/UserRegistration.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserRegistration(UserRegistrationViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User
                {
                    Nickname = model.Nickname,
                    Password = model.Password,  // Semplice password senza hashing, lo so che non va fatto ma mi dava troppi errori e non avevo più tempo ;(
                    Role = "User"
                };

                if (SaveUser(user))
                {
                    TempData["SuccessMessage"] = "Registrazione completata con successo!";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["ErrorMessage"] = "Si è verificato un errore durante la registrazione.";
                }
            }

            return View(model);
        }

        private bool SaveUser(User user)
        {
            string connectionString = GetConnectionString();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string query = @"
                INSERT INTO Users (Nickname, Password, Role)
                VALUES (@Nickname, @Password, @Role)";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Nickname", user.Nickname);
                    command.Parameters.AddWithValue("@Password", user.Password);
                    command.Parameters.AddWithValue("@Role", user.Role);

                    int rowsAffected = command.ExecuteNonQuery();

                    return rowsAffected > 0;
                }
            }
        }



        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = ValidateUser(model.Nickname, model.Password);

                if (user != null)
                {
                    FormsAuthentication.SetAuthCookie(user.Nickname, false);
                    return RedirectToAction("Index", "Home"); 
                }
                else
                {
                    ModelState.AddModelError("", "Nickname o Password errati.");
                }
            }

            return View(model);
        }


        private User ValidateUser(string nickname, string password)
        {
            User userInDb = GetUserFromDatabase(nickname);

            if (userInDb != null && password == userInDb.Password)
            {
                return userInDb;
            }

            return null;
        }

        private User GetUserFromDatabase(string nickname)
        {
            string connectionString = GetConnectionString();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string query = @"SELECT Nickname, Password, Role FROM Users WHERE Nickname = @Nickname";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Nickname", nickname);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return new User
                            {
                                Nickname = reader["Nickname"].ToString(),
                                Password = reader["Password"].ToString(),
                                Role = reader["Role"].ToString()
                            };
                        }
                    }
                }
            }

            return null;
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Corriere/Controllers/SpedizioniController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Corriere.Models;

namespace Corriere.Controllers
{
    public class SpedizioniController : Controller
    {
        private static string GetConnectionString()
        {
            return ConfigurationManager.ConnectionStrings["db"].ConnectionString;
        }




        public List<SpedizioneConCliente> GetSpedizioniWithClientNames()
        {
            List<SpedizioneConCliente> spedizioniWithClientNames = new List<SpedizioneConCliente>();

            using (SqlConnection conn = new SqlConnection(GetConnectionString()))
            {
                conn.Open();
                string query = @"
            SELECT S.*, C.Nome AS NomeCliente
            FROM Spedizioni S
            INNER JOIN Clienti C ON S.ClienteID = C.ClienteID";

                using (SqlCommand cmd = new SqlCommand(query, conn))
                {
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            SpedizioneConCliente spedizione = new SpedizioneConCliente
                            {
                                SpedizioneID = (int)reader["SpedizioneID"],
                                NumeroSpedizione = reader["NumeroSpedizione"].ToString(),
                                DataSpedizione = (DateTime)reader["DataSpedizione"],
                                Peso = (decimal)reader["Peso"],
                                CittaDestinataria = reader["CittaDestinataria"].ToString(),
                                IndirizzoDestinatario = reader["IndirizzoDestinatario"].ToString(),
                                NominativoDestinatario = reader["NominativoDestinatario"].ToString(),
                                Costo = (decimal)reader["Costo"],
                                DataConsegnaPrevista = (DateTime)reader["DataConsegnaPrevista"],
                                NomeCliente = reader["NomeCliente"].ToString(),
                                Stato = reader["Stato"].ToString()
                            };

                            spedizioniWithClientNames.Add(spedizione);
                        }
                    }
                }
            }

            return spedizioniWithClientNames;
        }






        public ActionResult Index()
        {
            List<SpedizioneConCliente> spedizioni = GetSpedizioniWithClientNames();
            return View(spedizioni);
        }




        public ActionResult NuovaSpedizione()
        {
            ViewBag.ClienteID = new SelectList(GetClienti(), "ClienteID", "Nome");
            ViewBag.StatiPossibili = GetStatiPossibili();
            return View();

        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NuovaSpedizione([Bind(Include = "SpedizioneID,ClienteID,NumeroSpedizione,DataSpedizione,Peso,CittaDestinataria,IndirizzoDestinatario,NominativoDestinatario,Costo,DataConsegnaPrevista,Stato")] Spedizione spedizione)
        {
            if (ModelState.IsValid)
            {
                if (IsValidSqlDateTime(spedizione.DataConsegnaPrevista))
                {
                    InserisciNuovaSpedizione(spedizione);
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("DataConsegnaPrevista", "La data prevista di consegna non è valida.");
                }
            }

            ViewBag.ClienteID = new SelectList(GetClienti(), "ClienteID", "Nome", spedizione.ClienteID);
            return View(spedizione);
        }



        // Funzione per verificare se una data è valida per SQL Server
        private bool IsValidSqlDateTime(DateTime value)
        {
            return (value >= SqlDateTime.MinValue.Value && value <= SqlDateTime.MaxValue.Value);
        }





        private List<string> GetStatiPossibili()
        {
            List<string> stati = new List<string>
    {
        "In transito",
        "In consegna",
        "Consegnato",
        "In Attesa"
    };
            return stati;
        }


        public ActionResult StatiPossibili()
        {
            ViewBag.StatiPossibili = GetStatiPossibili();
            return View();
        }


       

        private List<Cliente> GetClienti()
        {
            List<Cliente> clienti = new List<Cliente>();

            using (SqlConnection conn = new SqlConnection(GetConnectionString()))
            {
                conn.Open();
                string query = "SELECT * FROM Clienti";

                using (SqlCommand cmd = new SqlCommand(query, conn))
                {
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Cliente cliente = new Cliente
                            {
                                ClienteID = (int)reader["ClienteID"],
                                Nome = reader["Nome"].ToString(),
                            };
                            clienti.Add(cliente);
                        }
                    }
                }
            }

            return clienti;
        }





        private void InserisciNuovaSpedizione(Spedizione spedizione)
        {
            using (SqlConnection conn = new SqlConnection(GetConnectionString()))
            {
                conn.Open();

                string query = @"INSERT INTO Spedizioni (ClienteID, NumeroSpedizione, DataSpedizione, Peso, CittaDestinataria, IndirizzoDestinatario, NominativoDestinatario, Costo, DataConsegnaPrevista, Stato)
                                 VALUES (@ClienteID, @NumeroSpedizione, @DataSpedizione, @Peso, @CittaDestinataria, @IndirizzoDestinatario, @NominativoDestinatario, @Costo, @DataConsegnaPrevista, @Stato)";

                using (SqlCommand cmd = new SqlCommand(query, conn))
                {
                    cmd.Parameters.AddWithValue("@ClienteID", spedizione.ClienteID);
                    cmd.Parameters.AddWithValue("@NumeroSpedizione", spedizione.NumeroSpedizione);
                    cmd.Parameters.AddWithValue("@DataSpedizione", spedizione.DataSpedizione);
                    cmd.Parameters.AddWithValue("@Peso", spedizione.Peso);
                    cmd.Parameters.AddWithValue("@CittaDestinataria", spedizione.CittaDestinataria);
                    cmd.Parameters.AddWithValue("@IndirizzoDestinatario", spedizione.IndirizzoDestinatario);
                    cmd.Parameters.AddWithValue("@NominativoDestinatario", spedizione.NominativoDestinatario);
                    cmd.Parameters.AddWithValue("@Costo", spedizione.Costo);
                    cmd.Parameters.AddWithValue("@DataConsegnaPrevista", spedizione.DataConsegnaPrevista);
                    cmd.Parameters.AddWithValue("@Stato", spedizione.Stato);
                    cmd.ExecuteNonQuery();
                }
            }
        }





        private Spedizione GetSpedizioneById(int spedizioneID)
        {
            Spedizione spedizione = null;

            using (SqlConnection conn = new SqlConnection(GetConnectionString()))
            {
                conn.Open();

                string query = "SELECT * FROM Spedizioni WHERE SpedizioneID = @SpedizioneID";

                using (SqlCommand cmd = new SqlCommand(query, conn))
                {
                    cmd.Parameters.AddWithValue("@SpedizioneID", spedizioneID);

                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            spedizione = new Spedizione
                            {
                                SpedizioneID = (int)reader["SpedizioneID"],
                                ClienteID = (int)reader["ClienteID"],
                                NumeroSpedizione = reader["NumeroSpedizione"].ToString(),
                                DataSpedizione = (DateTime)reader["DataSpedizione"],
                                Peso = (decimal)reader["Peso"],
                                CittaDestinataria = reader["CittaDestinataria"].ToString(),
                                IndirizzoDestinatario = reader["IndirizzoDestinatario"].ToString(),
                                NominativoDestinatario = reader["NominativoDestinatario"].ToString(),
                                Costo = (decimal)reader["Costo"],
                                DataConsegnaPrevista = (DateTime)reader["DataConsegnaPrevista"],
                                Stato = reader["Stato"].ToString()
                            };
                        }
                    }
                }
            }

            return spedizione;
        }










        private Spedizione CercaSpedizione(string codiceFiscale, string numeroSpedizione)
        {
            Spedizione spedizione = null;

            using (SqlConnection conn = new SqlConnection(GetConnectionString()))
            {
                conn.Open();

                string query = "SELECT * FROM Spedizioni WHERE ClienteID = @ClienteID AND NumeroSpedizione = @NumeroSpedizione";

                using (SqlCommand cmd = new SqlCommand(query, conn))
                {
                    int clienteID = GetClienteIDByCodiceFiscale(codiceFiscale);

                    if (clienteID == -1)
                    {
                        return null;
                    }

                    cmd.Parameters.AddWithValue("@ClienteID", clienteID);
                    cmd.Parameters.AddWithValue("@NumeroSpedizione", numeroSpedizione);

                    using (SqlDataReader reader = cmd.ExecuteReader())

Corriere/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ufficio Pacchi </title>

    @Scripts.Render("~/bundles/modernizr")

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Corriere</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Verifica Stato", "VerificaStato", "Spedizioni", new { area = "" }, new { @class = "nav-link" })
                </li>


                @if (Request.IsAuthenticated)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Spedizioni", "Index", "Spedizioni", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Clienti", "Index", "Clienti", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    
                    <li class="nav-item dropdown">

                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            Queries
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" href="@Url.Action("SpedizioniInConsegna", "Spedizioni")">Spedizioni in Consegna Oggi</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("SpedizioniInAttesaView", "Spedizioni")">Spedizioni in Attesa</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("SpedizioniPerCittaView", "Spedizioni")">Spedizioni per Città Destinataria</a></li>
                        </ul>

                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Logout", "Logout", "Registration", new { area = "" }, new { @class = "nav-link" })
                    </li>
                }

            </ul>
        </div>
        
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ufficio Pacchi</p>
        </footer>
    </div>




    @Scripts.Render("~/bundles/jquery")
   
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    

</body>
</html>