Corriere/Controllers/ClientiController.cs
using System;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;
using Corriere.Models;

namespace Corriere.Controllers
{
    public class ClientiController : Controller
    {
        private static string GetConnectionString()
        {
            return ConfigurationManager.ConnectionStrings["db"].ConnectionString;
        }


        public ActionResult Index()
        {
            var clienti = CorriereDB.GetClienti(); 
            return View(clienti);
        }



        public ActionResult NuovoCliente()
        {
            return View();
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NuovoCliente(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    InserisciNuovoCliente(cliente);

                    TempData["Message"] = "Cliente aggiunto con successo.";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Si è verificato un errore durante l'aggiunta del cliente: " + ex.Message;
                }
            }

            return View(cliente);
        }





        private void InserisciNuovoCliente(Cliente cliente)
        {
            using (SqlConnection conn = new SqlConnection(GetConnectionString()))
            {
                conn.Open();

                string query = @"INSERT INTO Clienti (Nome, Cognome, CodiceFiscale, PartitaIVA)
                                 VALUES (@Nome, @Cognome, @CodiceFiscale, @PartitaIVA)";

                using (SqlCommand cmd = new SqlCommand(query, conn))
                {
                    cmd.Parameters.AddWithValue("@Nome", cliente.Nome);
                    cmd.Parameters.AddWithValue("@Cognome", cliente.Cognome);
                    cmd.Parameters.AddWithValue("@CodiceFiscale", cliente.CodiceFiscale);
                    cmd.Parameters.AddWithValue("@PartitaIVA", cliente.PartitaIVA);

                    cmd.ExecuteNonQuery();
                }
            }
        }


        public ActionResult Dettagli(int id)
        {
            Cliente cliente = CorriereDB.GetClienteById(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }






        public ActionResult ModificaCliente(int id)
        {
            Cliente cliente = CorriereDB.GetClienteById(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        [HttpPost]
       
        public ActionResult ModificaCliente(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                CorriereDB.UpdateCliente(cliente);
                TempData["Message"] = "Cliente modificato con successo.";
                return RedirectToAction("Index");
            }
            return View(cliente);
        }







        [HttpPost, ActionName("EliminaCliente")]
        
        public ActionResult EliminaClienteConfermato(int id)
        {
            var (success, message) = CorriereDB.EliminaCliente(id);
            TempData["Message"] = message;
            return RedirectToAction("Index");
        }


        [HttpGet]
        public JsonResult HaSpedizioniAttive(int clienteId)
        {
            bool haSpedizioni = CorriereDB.ClienteHaSpedizioniAttive(clienteId);
            return Json(haSpedizioni, JsonRequestBehavior.AllowGet);
        }








    }
}

Corriere/Views/Clienti/Dettagli.cshtml
@model Corriere.Models.Cliente

@{
    ViewBag.Title = "Dettagli Cliente";
}

<h2>Dettagli Cliente</h2>

<dl class="dl-horizontal">
    <dt>Nome:</dt>
    <dd>@Model.Nome</dd>

    <dt>Cognome:</dt>
    <dd>@Model.Cognome</dd>

    <dt>Codice Fiscale:</dt>
    <dd>@Model.CodiceFiscale</dd>

    <dt>Partita IVA:</dt>
    <dd>@Model.PartitaIVA</dd>
</dl>

<p>
    @Html.ActionLink("Torna all'elenco", "Index") |
    @Html.ActionLink("Modifica", "ModificaCliente", new { id = Model.ClienteID }) |
    
</p>

Corriere/Views/Clienti/Index.cshtml
@model IEnumerable<Corriere.Models.Cliente>

@{
    ViewBag.Title = "Elenco Clienti";
}

<h2>Elenco dei Clienti</h2>

<p>
    @Html.ActionLink("Nuovo Cliente", "NuovoCliente")
</p>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Cognome</th>
        <th>Codice Fiscale</th>
        <th>Partita IVA</th>
        <th></th>
    </tr>

    @foreach (var cliente in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => cliente.Nome)</td>
            <td>@Html.DisplayFor(modelItem => cliente.Cognome)</td>
            <td>@Html.DisplayFor(modelItem => cliente.CodiceFiscale)</td>
            <td>@Html.DisplayFor(modelItem => cliente.PartitaIVA)</td>
            <td>
                @Html.ActionLink("Dettagli", "Dettagli", new { id = cliente.ClienteID }) |
                @Html.ActionLink("Modifica", "ModificaCliente", new { id = cliente.ClienteID }) |
                <form action="@Url.Action("EliminaCliente", "Clienti")" method="post" data-cliente-id="@cliente.ClienteID" class="formEliminaCliente">
                    <input type="hidden" name="id" value="@cliente.ClienteID" />
                    <input type="submit" value="Elimina" />
                </form>


            </td>
        </tr>
    }
</table>
@section scripts {
    <script>
        $(document).on('submit', '.formEliminaCliente', function(e) {
            var form = $(this);
            var clienteId = form.data('cliente-id');

            
            if (form.data('confirmed')) {
                return true;
            }

            e.preventDefault();

            $.ajax({
                url: '@Url.Action("HaSpedizioniAttive", "Clienti")',
                data: { clienteId: clienteId },
                method: 'GET',
                success: function(data) {
                    if (data) {
                        alert("Il cliente ha spedizioni attive, gestire prima le spedizioni e poi eliminare il cliente");
                    } else {
                        if (confirm('Sei sicuro di voler eliminare questo cliente?')) {
                            form.data('confirmed', true).submit();
                        }
                    }
                },
                error: function(error) {
                    console.log(error);
                }
            });
        });
    </script>
}

Corriere/Views/Clienti/ModificaCliente.cshtml
@model Corriere.Models.Cliente

@{
    ViewBag.Title = "Modifica Cliente";
}

<h2>Modifica Cliente</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ClienteID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cognome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cognome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cognome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodiceFiscale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodiceFiscale, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodiceFiscale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartitaIVA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartitaIVA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartitaIVA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salva" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna all'elenco", "Index")
</div>

Corriere/Views/Clienti/NuovoCliente.cshtml
@model Corriere.Models.Cliente

@{
    ViewBag.Title = "Nuovo Cliente";
}

<h2>Nuovo Cliente</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cognome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cognome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cognome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodiceFiscale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodiceFiscale, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodiceFiscale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartitaIVA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartitaIVA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartitaIVA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salva" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna alla lista", "Index")
</div>